# This is a basic workflow to help you get started with Actions

name: Deploy TimeWeb Hosting
run-name: ${{ github.actor }} is testing out GitHub Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.13.2 ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Установка зависимостей
          run: npm install

      - name: Собираем проект
          run: npm run build

      - name: Отправляем на хостинг
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
            server: ${{ secrets.FTP_SERVER }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            server-dir: /vue-eks-2002/public_html/
